### ISSUE TITLE
WSJ

### ISSUE THREAD

**Issue by TimAAPL** [SJDunkelman/newspaper_scraper#10]
https://www.wsj.com/news/archive/20200416

clear format, date is at the end of the URL

**Comment by SJDunkelman** [comment]
Which topics shall we restrict this to? We need to standardise what we extract from each news source so we don't double count coverage. For example you have 'U.S' but also 'Tri-state area' and 'U.S. Economy'

**Comment by SJDunkelman** [comment]
This issue is now complete - can further edit topics by changing topic list in WSJ class
